### ISSUE TITLE
npm test failed

### ISSUE THREAD

**Issue by argonlaser** [wordist/wordist.xyz#32]
Need to include the server file one level up the directory.

**Comment by argonlaser** [comment]
ERR LOG 

E:\PROJECT\wordist.xyz>npm test
wordist.xyz@1.0.0 test E:\PROJECT\wordist.xyz
lab -a code -c
module.js:327
throw err;
^
Error: Cannot find module '../../server'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (E:\PROJECT\wordist.xyz\test\api\v1\users.js:11:16)
at Module._compile (module.js:409:26)
at Object.require.extensions.(anonymous function) [as .js] (E:\PROJECT\wordist.xyz\node_modules\lab\lib\coverage.js:36
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at E:\PROJECT\wordist.xyz\node_modules\lab\lib\cli.js:120:21
at Array.forEach (native)
at Object.internals.traverse.paths.forEach.testFiles [as traverse] (E:\PROJECT\wordist.xyz\node_modules\lab\lib\cli.js
at Object.exports.run (E:\PROJECT\wordist.xyz\node_modules\lab\lib\cli.js:61:31)
at Object.<anonymous> (E:\PROJECT\wordist.xyz\node_modules\lab\bin\lab:5:23)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:139:18)
at node.js:968:3
npm ERR! Test failed. See above for more details.

**Comment by argonlaser** [comment]
https://github.com/wordist/wordist.xyz/pull/33 addresses this.
